parameters:
#    ens_forum.example.class: Ens\ForumBundle\Example

services:
#    ens_forum.example:
#        class: %ens_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
